---
name: Build Fedora Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: "Get version"
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${{ github.event.head_commit.message }} | sed 's/ \[rel\]//')

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Get Kernel"
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "sharpenedblade/t2linux-fedora-kernel"
          tag: "5.18.9-200"
          fileName: "*.rpm"
          tarBall: false
          zipBall: false
      
      - name: "Build"
        run: |
          docker run -t -v "$PWD":/repo fedora:35 /bin/bash -c "/repo/build.sh"

      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: t2linux-fedora-iso-${{ steps.get_version.outputs.VERSION }}
          path: ${{ github.workspace }}/output/*

      - name: Release
        if: ${{ github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[rel]') }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/output/*
          tag_name: ${{ steps.get_version.outputs.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
